services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dx_snap_server
      POSTGRES_PASSWORD: dx_snap_on_top
      POSTGRES_DB: dx_snap_db
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://dx_snap_server:dx_snap_on_top@db:5432/dx_snap_db"
    command: ["./dx_snap_server"]

